version: "3.9"

networks:
  gotte-net:
    external: true

services:
  fastapi:
    build: .
    container_name: fastapi
    restart: unless-stopped
    environment:
      PORT: 8000
    ports:
      - 8000:8000
    networks:
      gotte-net:
        ipv4_address: 190.160.0.204